apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appLabel }}-v1
  labels:
    app: {{ .Values.appLabel }}
    version: v1
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ .Values.appLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.appLabel }}
        version: v1
    spec:
      containers:
      - image: {{ .Values.image.registry }}/{{ .Values.image.username }}/{{ .Values.image.repo }}:{{ .Values.image.tag1 }}
        name: {{ .Values.appLabel }}
        ports:
        - containerPort: {{ .Values.containerPort }}
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: MYSQL_USER
              name: db-creds
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_PASSWORD
              name: db-creds