apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-cert
  namespace: {{ .Values.namespace }}
spec:
  secretName: {{ .Values.secretName }}
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames: {{ .Values.dnsNames }}