apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-cert
  namespace: ingress-nginx
spec:
  secretName: app-george-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - my.app-george.com