apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-app
  labels:
    app: wordpress-app
    version: v1
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: wordpress-app
  template:
    metadata:
      labels:
        app: wordpress-app
        version: v1
    spec:
      containers:
      - image: wordpress:cli-php8.3
        name: wordpress-app
        ports:
        - containerPort: 80
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: MYSQL_USER
              name: db-creds
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_PASSWORD
              name: db-creds
        - name: WORDPRESS_DB_HOST
          value: {{ .Values.host }}
        - name: WORDPRESS_DB_NAME
          value: {{ .Values.database }}