apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress-ingress
  annotations:
    nginx.ingress.kubernetes.io/limit-rps: "10"
    nginx.ingress.kubernetes.io/denylist-source-range: "0.0.0.0"
    nginx.ingress.kubernetes.io/allowlist-source-range: "192.168.1.0/24"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /wordpress
        pathType: Exact
        backend:
          service:
            name: wordpress-app
            port:
              number: 80
      - path: /flask
        pathType: Exact
        backend:
          service:
            name: flask-app
            port:
              number: 5000