apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress-ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /wordpress
        pathType: Exact
        backend:
          service:
            name: wordpress-app
            port:
              number: 80
      - path: /flask
        pathType: Exact
        backend:
          service:
            name: flask-app
            port:
              number: 5000