apiVersion: v1
kind: Service
metadata:
  name: wordpress-app
  labels:
    app: wordpress-app
    service: wordpress-app
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: wordpress-app